datasources:
  default:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVERCLASSNAME}
    driver-class-name: ${DB_DRIVERCLASSNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
jpa:
  default:
    packages-to-scan:
      - 'io.eventuate.examples.tram.sagas.ordersandcustomers.customers'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
micronaut:
  router:
    static-resources:
      swagger-ui:
        paths: classpath:swagger-ui
        mapping: /swagger-ui/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
